server:
  port: 8081
  context-path: /dubbo-provider

# dubbo config
# 参考：https://github.com/alibaba/dubbo-spring-boot-starter/blob/master/README_zh.md
spring:
  application:
    name: dubbo-spring-boot-starter
  dubbo:
    server: true
    registry: zookeeper://dev.tss.com:2181